app/flask_conf/models.py
import os
import sys  
from pathlib import Path
from functools import wraps

file = Path(__file__).resolve() 
package_root_directory = file.parents[1]
sys.path.append(str(package_root_directory))

from flask_conf import db

class Currency(db.Model):
	id = db.Column(db.Integer(),primary_key = True)
	charcode = db.Column(db.String(20), unique = False, nullable = False)
	value = db.Column(db.Float(), unique = False, nullable = False)
	date = db.Column(db.Integer(), unique = False, nullable = False)

	def __init__(self,*args,**kwargs):
		super(Currency,self).__init__(*args,**kwargs)

	@property
	def get_id(self):
		return self.id

	@property
	def get_charcode(self):
		return self.charcode

	@property
	def get_value(self):
		return self.value

	def date_decorator(func):
		from utils.utils import number_to_date
		@wraps(func)
		def wrapper(*args,**kwargs):
			date_number = func(*args,**kwargs)
			str_date = number_to_date(date_number)
			return str_date
		return wrapper

	@property
	@date_decorator
	def get_date(self):
		return self.date

	def dict_object(self):
		return {'charcode':self.charcode, 'value':self.value, 'date':self.get_date}


	def __repr__(self):
		return f'id={self.id}, charcode={self.charcode},value={self.value}, date={self.get_date}'

class Covid(db.Model):
	id = db.Column(db.Integer(),primary_key = True)
	Province_State = db.Column(db.String(50),unique = False, nullable = True)
	Country_Region = db.Column(db.String(50), unique = False, nullable = False)
	Confirmed = db.Column(db.Integer(), unique = False, nullable = True)
	Recovered = db.Column(db.Integer(), unique = False, nullable = True)
	Deaths = db.Column(db.Integer(), unique = False, nullable = True)
	Active = db.Column(db.Integer(), unique = False, nullable = True)
	Last_update = db.Column(db.Integer(), unique = False, nullable = False)

	def __init__(self, *args,**kwargs):
		super(Covid,self).__init__(*args,**kwargs)

	def __repr__(self):
		return (
				f'''id = {self.id}, Province_State = {self.Province_State}, Country_Region = {self.Country_Region}'
				Confirmed = {self.Confirmed}, Recovered = {self.Recovered}, Deaths = {self.Deaths},
				Active = {self.Active}, Last_update = {self.Last_update}'''
				)

app/flask_conf/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_conf.config import Config
from pathlib import Path
import sys

file = Path(__file__).resolve()
package_root_directory = file.parents[1]
sys.path.append(str(package_root_directory))

TEMPLATE_DIR = str(package_root_directory)+'/templates'
STATIC_DIR = str(package_root_directory)+'/static'

app = Flask(__name__, template_folder=TEMPLATE_DIR, static_folder=STATIC_DIR)
app.config.from_object(Config)
db = SQLAlchemy(app)
REPORTERS_CONNECTION_ERROR = {'connection_error':'check internet connection or page not found...'}

from views.main_routes import main
from views.currency_routes import currency
from views.covid_routes import covid
from errors.handlers import errors

app.register_blueprint(main)
app.register_blueprint(currency)
app.register_blueprint(covid)
app.register_blueprint(errors)


def database_is_exists(url = app.config['SQLALCHEMY_DATABASE_URI']):
	"""
	check if database is exists, if not -> being created
	"""
	from sqlalchemy import create_engine
	from sqlalchemy_utils.functions import database_exists, create_database
	engine = create_engine(url, echo = True)
	if not database_exists(url):
		create_database(engine.url)

def create_app(config_class = Config):
	return app

app/main.py
from flask_conf import create_app

app = create_app()

if __name__ == '__main__':
	app.run(host = "0.0.0.0", port = 8080, debug = False)

app/views/covid_routes.py
from flask import request, render_template, Blueprint
import sys
from pathlib import Path
import pandas as pd
import plotly
import plotly.express as px
import plotly.graph_objects as go
import json

file = Path(__file__).resolve()
package_root_directory = file.parents[1]
sys.path.append(str(package_root_directory))

covid = Blueprint('covid_news', __name__)

from views.main_routes import create_news

def fetch_covid_data():
	results = create_news()
	fetch_results = next((filter(lambda i:'covid_news' in i.keys() ,results)))
	if not fetch_results:
		fetch_results = 'covid data is empty...'
	return fetch_results

def deaths_plot(covid_top5_deaths):
	covid_top5_deaths = [i.get('attributes') for i in covid_top5_deaths]
	data = pd.DataFrame(covid_top5_deaths)
	fig = px.bar(data, x = 'Deaths', y = data.Country_Region, height = 600, color = 'Deaths', orientation = 'h',
				color_continuous_scale = ['deepskyblue','red'])
	fig.update_layout(xaxis_title = None, yaxis_title=None)
	json_bar = fig.to_json()
	return json_bar

def active_plot(covid_top5_actives):
	covid_top5_actives = [i.get('attributes') for i in covid_top5_actives]
	data = pd.DataFrame(covid_top5_actives)
	fig = px.scatter(data, x = data.Country_Region, y = data.Active, size = 'Active', size_max = 60,
				color = data.index)
	fig.update_layout(xaxis_title = None, yaxis_title=None)
	json_scatter = fig.to_json()
	return json_scatter

def confirmed_plot(covid_top5_confirmed):
	covid_top5_confirmed = [i.get('attributes') for i in covid_top5_confirmed]
	data = pd.DataFrame(covid_top5_confirmed)
	fig = px.scatter(data, x = data.Country_Region, y = data.Confirmed, size = 'Confirmed', size_max = 60,
				color = data.index)
	fig.update_layout(xaxis_title = None, yaxis_title=None)
@covid.route("/covid-news")
def covid_route():
	covid_news = fetch_covid_data().get('covid_news')
	covid_deaths = deaths_plot(covid_news[0].get('deaths'))
	covid_active = active_plot(covid_news[1].get('active'))
	covid_confirmed = active_plot(covid_news[2].get('confirmed'))
	return render_template('covid.html', title = 'Covid news', covid_deaths_json = covid_deaths,
								covid_active_json = covid_active,
								covid_confirmed_json = covid_confirmed)

app/views/currency_routes.py
from flask import request, render_template, Blueprint
import sys
from pathlib import Path
import pandas as pd
import plotly as px
import plotly.graph_objects as go
import json

file = Path(__file__).resolve()
package_root_directory = file.parents[1]
sys.path.append(str(package_root_directory))

currency = Blueprint('currency_news', __name__)

def get_currency_from_db():
	from flask_conf.models import db, Currency
	currency = Currency.query.all()
	return currency

def currency_plots(currency_from_db):
	from reporters.currency_reporter import CURRENCY_OF_INTEREST
	currency_from_db = [i.dict_object() for i in currency_from_db]
	currency_from_db = pd.DataFrame(currency_from_db)
	plots = go.Figure()
	for i in CURRENCY_OF_INTEREST:
		sorted_by_name = currency_from_db[currency_from_db['charcode']==i]
		plots.add_trace(go.Scatter(x = sorted_by_name['date'], y = sorted_by_name['value'], name = i))
	graphJSON = json.dumps(plots, cls=px.utils.PlotlyJSONEncoder)
	return graphJSON

@currency.route("/currency-news")
def currency_route():
	currency_from_db = get_currency_from_db()
	currency_plots_json = currency_plots(currency_from_db)
	return render_template('currency.html', title = 'Currency news', currency_plots_json = currency_plots_json)

app/views/main_routes.py
from flask import request, render_template, Blueprint
import sys
import asyncio
from pathlib import Path

file = Path(__file__).resolve()
package_root_directory = file.parents[1]
sys.path.append(str(package_root_directory))

main = Blueprint('main', __name__)


def create_news():
	from redactors.newsmaker import newsmaker_run
	from flask_conf import database_is_exists
	database_is_exists()
	results = asyncio.run(newsmaker_run())
	return results

def parce_results():
	results = create_news()
	parced_results = {}
	parced_results['covid_news'] = next((filter(lambda i:'covid_news' in i.keys() ,results)))
	parced_results['currency_news'] = next((filter(lambda i:'currency_news' in i.keys() ,results)))
	return parced_results

@main.route("/")
def index():
	results = parce_results()
	covid = results.get('covid_news').get('covid_news')[0].get('deaths')
	currency = results.get('currency_news').get('currency_news')
	currency_latest_update = currency.pop('Date')
	return render_template('main.html', title = 'News page', 
						currency_latest_update = currency_latest_update,
						currency = currency,
						covid = covid)

@main.route("/about")
def about():
	return render_template('about.html', title = 'About page')

app/templates/about.html
{% extends "plots_layout.html" %}

{% block content %}
	
	<div class="container">
	
		<h3>About page info</h3>
	
	</div>

{% endblock content %}

app/templates/covid.html
{% extends "plots_layout.html" %}

{% block content %}
	
	<!-- DEATHS CHART HERE -->
	<div class="container">

		<h3 style="font-weight: 100%;">Top 5 covid deaths chart</h3>

	<div id="deaths_bar" class="chart"></div>

	</div>

	<!-- ACTIVE CHART HERE -->

	<div class="container">

		<h3 style="font-weight: 100%;">Top 5 covid active cases chart</h3>

	<div id="active_scatter" class="chart"></div>

	</div>

	<!-- CONFIRMED CHART HERE -->

	<div class="container">

		<h3 style="font-weight: 100%;">Top 5 covid confirmed cases chart</h3>

	<div id="confirmed_scatter" class="chart"></div>

	</div>

	<script type="text/javascript">
		var graphs = {{ covid_deaths_json|safe }};
		Plotly.plot('deaths_bar', graphs, {});        
	</script>

	<script type="text/javascript">
		var graphs = {{ covid_active_json|safe }};
		Plotly.plot('active_scatter', graphs, {});   
	</script>

	<script type="text/javascript">
		var graphs = {{ covid_confirmed_json|safe }};
		Plotly.plot('confirmed_scatter', graphs, {});
	</script>

{% endblock content %}

app/templates/currency.html
{% extends "plots_layout.html" %}

{% block content %}
	

	<div class="container">			

		<h3 style="font-weight: 100%;">Currency trends</h3>

		<div id="chart" class="chart"></div>

	</div>

	<script type="text/javascript">
		var graphs = {{ currency_plots_json|safe }};
		Plotly.plot('chart', graphs, {});
	</script>

{% endblock content %}

app/templates/main.html
{% extends "main_layout.html" %}

{% block currency %}

  <p class="lead">Information on date: {{ currency_latest_update }}</p>
  <table style="border:none;">
  {% for i in currency.items() %}  
    <tr>
      <td>{{ i[0] }}/RUB: </td>
      <td>{{ i[1].get('Value') }}</td>
    </tr>    
  {% endfor %}
  </table>
  
{% endblock currency %}

{% block covid %}

  <p class="lead">Information on today:</p>
  <table>    
  {% for i in covid %} 
    <tr>
      <td>{{ i['attributes']['Country_Region'] }}</td>
    </tr> 
  {% endfor %}
  </table>

{% endblock covid%}

app/templates/main_layout.html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
		<meta name="generator" content="Hugo 0.83.1">
		{% if title %}
			<title>News:{{ title }}</title>
		{% else %}
			<title>News:home page</title>
		{% endif %}
		<link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

		<!-- Bootstrap core CSS -->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	<style>
		.image_placeholder{
	 background: url('loading.gif') no-repeat;
	 width:500px;
	 height:500px;
	}
	</style>

		<!-- Custom styles for this template -->
				<link rel="stylesheet" type = "text/css" href="{{ url_for('static', filename = 'carousel.rtl.css') }}">
	</head>

<body>

<header>
	<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ url_for('main.index') }}">News</a>
		</div>
	</nav>
</header>

<main>
		<!-- currency section -->
		<hr class="featurette-divider">

		<div class="row featurette">
			<div class="col-md-7">
				<h3 class="featurette-heading">Currency rates today.<span class="text-muted">Latest information from center bank.</span></h3>
				{% block currency %}{% endblock currency %}
			</div>
			<div class="col-md-5">
				<img class = "image_placeholder" src="{{ url_for('static', filename='currency_label.jpg') }}">
				<p><a class="btn btn-secondary" href="{{ url_for('currency_news.currency_route') }}">View details &raquo;</a></p>
			</div>
		</div>

		<!-- covid section -->

		<hr class="featurette-divider">

		<div class="row featurette">
			<div class="col-md-7">
				<h3 class="featurette-heading">Daily covid news.<span class="text-muted">Top 5 most deaths countries</span></h3>
				{% block covid %}{% endblock covid%}
			</div>
			<div class="col-md-5">
				<img class = "image_placeholder" src="{{ url_for('static', filename='covid_label.jpg') }}">
				<p><a class="btn btn-secondary" href="{{ url_for('covid_news.covid_route') }}">View details &raquo;</a></p>
			</div>
		</div>
	</div>

		<!-- /END THE FEATURETTES -->

	<!-- FOOTER -->
	<footer class="container">
		<p class="float-end"><a href="#">Back to top</a></p>
		<p>&copy; 2017–2021 Company, Inc. &middot; <a href="{{ url_for('main.about') }}">About</a> &middot; <a href="#">Terms</a></p>
	</footer>
	</main>
	</body>
</html>

app/templates/plots_layout.html
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
		<meta name="generator" content="Hugo 0.83.1">

		{% if title %}
			<title>News:{{ title }}</title>
		{% else %}
			<title>News:news page</title>
		{% endif %}

		<link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">
		<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

		<!-- Bootstrap core CSS -->

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
		<style>
			.bd-placeholder-img {
				font-size: 1.125rem;
				text-anchor: middle;
				-webkit-user-select: none;
				-moz-user-select: none;
				user-select: none;
			}

			@media (min-width: 768px) {
				.bd-placeholder-img-lg {
					font-size: 3.5rem;
				}
			}
				.container{
					margin-top:60px;
				}
		</style>

	</head>

		<body>
			<header>
				<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
					<div class="container-fluid">
						<a class="navbar-brand" href="{{ url_for('main.index') }}">News</a>
					</div>
				</nav>
			</header>
			{% block content %}{% endblock content %}
		</body>
</html>